### PR TITLE
Add block breaking handler for potion effect system

### LINKED ISSUE #2: Add handler for block breaking
Pretty self-explanatory, handle block breaks and give a random effect every time a block is broken.

### PR DESCRIPTION
**Pull request by sh0ckR6**
Resolves #2 

Gives the player a random potion effect every time they break a block

### CODE REVIEW

**Comment by sh0ckR6** [comment]
Need some opinions on this before I mark it as ready for review. 

Should the random potion effects also have random durations/amplifiers? If so, should this be configurable as well? Just looking for some thoughts on this before I merge.

**Comment by sh0ckR6** [comment]
> I think the duration and amplifiers should be random, and configurable.

Yeah, I was thinking that as well. Just makes more sense to be a little more fun with the randomness :D

> Default values should at least be tweaked so that you can't get a Harming Potion of actual death but at least close.

So you're saying I should remove the option to get the `Instant Damage` potion effect if the player would be killed by it? Would this also apply to Wither as well?

Should all damage effects that would kill the player be removed from the list? Just throwing out things that could happen if I go with this and wondering where the line should be drawn if any?

**Comment by sh0ckR6** [comment]
@gtaEPIC if you can, would you mind giving this a quick review just to quickly check over the effect constraints?

Configuration won't be added until the config system has been implemented so that'll be merged in a different PR.

**Review by gtaEPIC — APPROVED** [review]
Looks good to me.
Also nice `clamp` :)

**Pull request merged**
